apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-consumer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-consumer
  template:
    metadata:
      labels:
        app: springboot-consumer
    spec:
      containers:
      - name: springboot-consumer
        image: localhost:5000/springboot-consumer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
# Opcional: Service si necesitas exponer algo
apiVersion: v1
kind: Service
metadata:
  name: springboot-consumer
  namespace: kafka
spec:
  selector:
    app: springboot-consumer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080